### ISSUE TITLE
validacion de campos

### ISSUE THREAD

**Issue by emaleboni** [enfermosdelpadel/backoffice#17]
Validar en los campos de carga de item que solo se pueda poner la info que se solicita por ejemplo en los campos numericos, solo numeros.

**Comment by mdcravero** [comment]
Se estableció cada input en su tipo, en el tipo numérico, solo acepta números

**Comment by mdcravero** [comment]
La carga en su mayoría se hace con desplegables para evitar errores, y los campos de cantidad y valor, solo permiten campos numéricos.
